name: Build Application

on:
  push:
    branches: [ main, master, develop, feature/* ]
  pull_request:
    branches: [ main, master, develop ]
  workflow_dispatch:

env:
  DOTNET_VERSION: '9.0.x'

jobs:
  build:
    name: Build .NET Application
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        
    - name: Restore dependencies
      run: dotnet restore backend.sln
      
    - name: Build solution
      run: dotnet build backend.sln --no-restore --configuration Release
      
    - name: Run tests (if any)
      run: dotnet test backend.sln --no-build --verbosity normal --configuration Release
      continue-on-error: true # Continue even if no tests exist
      
    - name: Publish application
      run: dotnet publish backend.API/backend.API.csproj -c Release -o ./publish
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: backend-app
        path: ./publish
        retention-days: 7
        
    - name: Build status
      run: echo "✅ Build completed successfully!"
