name: Notify Team

on:
  workflow_run:
    workflows: ["Build Application"]
    types: [completed]
  workflow_dispatch:
    inputs:
      build_status:
        description: 'Build status (success/failure)'
        required: true
        type: string
        default: 'success'
      message:
        description: 'Custom message to send'
        required: false
        type: string

env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  SLACK_CHANNEL: '#general'

permissions:
  actions: read
  contents: read

jobs:
  notify-workflow-run:
    name: Send Slack Notification (Workflow Run)
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_run'
    
    steps:
    - name: Get workflow run info
      id: workflow_run
      uses: actions/github-script@v7
      with:
        script: |
          const run = await github.rest.actions.getWorkflowRun({
            owner: context.repo.owner,
            repo: context.repo.repo,
            run_id: context.event.workflow_run.id
          });
          
          const conclusion = run.data.conclusion || 'unknown';
          const status = conclusion === 'success' ? 'success' : 'failure';
          
          core.setOutput('status', status);
          core.setOutput('run_id', run.data.id);
          core.setOutput('commit_sha', run.data.head_sha);
          core.setOutput('branch', run.data.head_branch);
          core.setOutput('conclusion', conclusion);
          
          return { status, run_id: run.data.id, commit_sha: run.data.head_sha, branch: run.data.head_branch };
    
    - name: Debug workflow run info
      run: |
        echo "Status: ${{ steps.workflow_run.outputs.status }}"
        echo "Run ID: ${{ steps.workflow_run.outputs.run_id }}"
        echo "Commit SHA: ${{ steps.workflow_run.outputs.commit_sha }}"
        echo "Branch: ${{ steps.workflow_run.outputs.branch }}"
    
    - name: Notify Slack - Success (Workflow Run)
      if: steps.workflow_run.outputs.status == 'success'
      uses: 8398a7/action-slack@v3
      with:
        status: success
        webhook_url: ${{ env.SLACK_WEBHOOK_URL }}
        channel: ${{ env.SLACK_CHANNEL }}
        text: "✅ Build successful for ${{ github.repository }}#${{ steps.workflow_run.outputs.run_id }}"
        fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
        mention_users: ${{ github.actor }}
        
    - name: Notify Slack - Failure (Workflow Run)
      if: steps.workflow_run.outputs.status == 'failure'
      uses: 8398a7/action-slack@v3
      with:
        status: failure
        webhook_url: ${{ env.SLACK_WEBHOOK_URL }}
        channel: ${{ env.SLACK_CHANNEL }}
        text: "❌ Build failed for ${{ github.repository }}#${{ steps.workflow_run.outputs.run_id }}"
        fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
        mention_users: ${{ github.actor }}
        
    - name: Notify Slack - Unknown Status (Workflow Run)
      if: steps.workflow_run.outputs.status == 'unknown'
      uses: 8398a7/action-slack@v3
      with:
        status: custom
        webhook_url: ${{ env.SLACK_WEBHOOK_URL }}
        channel: ${{ env.SLACK_CHANNEL }}
        text: "❓ Build status unknown for ${{ github.repository }}#${{ steps.workflow_run.outputs.run_id }}"
        fields: repo,message,commit,author,action,eventName,ref,workflow,job,took

  notify-manual:
    name: Send Slack Notification (Manual)
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    
    steps:
    - name: Debug manual trigger
      run: |
        echo "Event name: ${{ github.event_name }}"
        echo "Build status: ${{ github.event.inputs.build_status }}"
        echo "Run ID: ${{ github.run_id }}"
        echo "Commit SHA: ${{ github.sha }}"
        echo "Branch: ${{ github.ref_name }}"
    
    - name: Notify Slack - Success (Manual)
      if: github.event.inputs.build_status == 'success'
      uses: 8398a7/action-slack@v3
      with:
        status: success
        webhook_url: ${{ env.SLACK_WEBHOOK_URL }}
        channel: ${{ env.SLACK_CHANNEL }}
        text: "✅ Manual notification: Build successful for ${{ github.repository }}#${{ github.run_id }}"
        fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
        mention_users: ${{ github.actor }}
        
    - name: Notify Slack - Failure (Manual)
      if: github.event.inputs.build_status == 'failure'
      uses: 8398a7/action-slack@v3
      with:
        status: failure
        webhook_url: ${{ env.SLACK_WEBHOOK_URL }}
        channel: ${{ env.SLACK_CHANNEL }}
        text: "❌ Manual notification: Build failed for ${{ github.repository }}#${{ github.run_id }}"
        fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
        mention_users: ${{ github.actor }}
