name: Notify Team

on:
  workflow_run:
    workflows: ["Build Application"]
    types: [completed]
  workflow_dispatch:
    inputs:
      build_status:
        description: 'Build status (success/failure)'
        required: true
        type: string
        default: 'success'
      message:
        description: 'Custom message to send'
        required: false
        type: string

env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  SLACK_CHANNEL: '#general'

permissions:
  actions: read
  contents: read

jobs:
  notify-workflow-run:
    name: Send Slack Notification (Workflow Run)
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_run'
    env:
      TRIGGERING_WORKFLOW_ID: ${{ github.event.workflow_run.id }}
      TRIGGERING_WORKFLOW_NAME: ${{ github.event.workflow_run.name }}
      TRIGGERING_WORKFLOW_CONCLUSION: ${{ github.event.workflow_run.conclusion }}
      TRIGGERING_WORKFLOW_HEAD_SHA: ${{ github.event.workflow_run.head_sha }}
      TRIGGERING_WORKFLOW_HEAD_BRANCH: ${{ github.event.workflow_run.head_branch }}
    
    steps:
    - name: Debug workflow run info
      run: |
        echo "Triggering Workflow ID: ${{ env.TRIGGERING_WORKFLOW_ID }}"
        echo "Triggering Workflow Name: ${{ env.TRIGGERING_WORKFLOW_NAME }}"
        echo "Triggering Workflow Conclusion: ${{ env.TRIGGERING_WORKFLOW_CONCLUSION }}"
        echo "Triggering Workflow Head SHA: ${{ env.TRIGGERING_WORKFLOW_HEAD_SHA }}"
        echo "Triggering Workflow Head Branch: ${{ env.TRIGGERING_WORKFLOW_HEAD_BRANCH }}"
    
    - name: Notify Slack - Success (Workflow Run)
      if: env.TRIGGERING_WORKFLOW_CONCLUSION == 'success'
      uses: 8398a7/action-slack@v3
      with:
        status: success
        webhook_url: ${{ env.SLACK_WEBHOOK_URL }}
        channel: ${{ env.SLACK_CHANNEL }}
        text: "✅ Build successful for ${{ github.repository }}#${{ env.TRIGGERING_WORKFLOW_ID }}"
        fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
        mention_users: ${{ github.actor }}
        
    - name: Notify Slack - Failure (Workflow Run)
      if: env.TRIGGERING_WORKFLOW_CONCLUSION == 'failure'
      uses: 8398a7/action-slack@v3
      with:
        status: failure
        webhook_url: ${{ env.SLACK_WEBHOOK_URL }}
        channel: ${{ env.SLACK_CHANNEL }}
        text: "❌ Build failed for ${{ github.repository }}#${{ env.TRIGGERING_WORKFLOW_ID }}"
        fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
        mention_users: ${{ github.actor }}
        
    - name: Notify Slack - Unknown Status (Workflow Run)
      if: env.TRIGGERING_WORKFLOW_CONCLUSION != 'success' && env.TRIGGERING_WORKFLOW_CONCLUSION != 'failure'
      uses: 8398a7/action-slack@v3
      with:
        status: custom
        webhook_url: ${{ env.SLACK_WEBHOOK_URL }}
        channel: ${{ env.SLACK_CHANNEL }}
        text: "❓ Build status unknown for ${{ github.repository }}#${{ env.TRIGGERING_WORKFLOW_ID }}"
        fields: repo,message,commit,author,action,eventName,ref,workflow,job,took

  notify-manual:
    name: Send Slack Notification (Manual)
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    
    steps:
    - name: Debug manual trigger
      run: |
        echo "Event name: ${{ github.event_name }}"
        echo "Build status: ${{ github.event.inputs.build_status }}"
        echo "Run ID: ${{ github.run_id }}"
        echo "Commit SHA: ${{ github.sha }}"
        echo "Branch: ${{ github.ref_name }}"
    
    - name: Notify Slack - Success (Manual)
      if: github.event.inputs.build_status == 'success'
      uses: 8398a7/action-slack@v3
      with:
        status: success
        webhook_url: ${{ env.SLACK_WEBHOOK_URL }}
        channel: ${{ env.SLACK_CHANNEL }}
        text: "✅ Manual notification: Build successful for ${{ github.repository }}#${{ github.run_id }}"
        fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
        mention_users: ${{ github.actor }}
        
    - name: Notify Slack - Failure (Manual)
      if: github.event.inputs.build_status == 'failure'
      uses: 8398a7/action-slack@v3
      with:
        status: failure
        webhook_url: ${{ env.SLACK_WEBHOOK_URL }}
        channel: ${{ env.SLACK_CHANNEL }}
        text: "❌ Manual notification: Build failed for ${{ github.repository }}#${{ github.run_id }}"
        fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
        mention_users: ${{ github.actor }}
