name: Slack Notification

on:
  workflow_call:
    inputs:
      status:
        required: true
        type: string
        description: 'Build status (success/failure)'
      message:
        required: false
        type: string
        description: 'Custom message to send'
      channel:
        required: false
        type: string
        description: 'Slack channel to send notification to'
        default: '#general'
    secrets:
      slack-webhook:
        required: true
        description: 'Slack webhook URL'

jobs:
  notify:
    name: Send Slack Notification
    runs-on: ubuntu-latest
    
    steps:
    - name: Notify Slack
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ inputs.status }}
        webhook_url: ${{ secrets.slack-webhook }}
        channel: ${{ inputs.channel }}
        text: ${{ inputs.message }}
        fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
        mention_users: ${{ github.actor }}
